sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

# GKE
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project birdboard-k8s-258109
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials birdboard-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t noalistic/birdboard-test -f Dockerfile .

script:
  - docker run -e CI=true noalistic/birdboard-test vendor/bin/phpunit

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
